server:
  port: 8080
  servlet:
    context-path: /hoso
    session:
      timeout: 5m
spring:
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  #  datasource:
  #    url: jdbc:mysql://120.79.88.98:3306/hosoneu?characterEncoding=utf-8&serverTimezone=GMT%2B8
  #    username: root
  #    password: 123456
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #  操作自己本地数据库进行测试
  #  datasource:
  #    #    url: jdbc:mysql://120.79.88.98:3306/hosoneu?characterEncoding=utf-8&serverTimezone=GMT%2B8
  #    #    29-y的url：@author 29-y 本地数据库地址 @time 2019.06.10
  #    #    url: jdbc:mysql://localhost:3306/hoso_local_dev?characterEncoding=utf-8&serverTimezone=GMT%2B8
  #
  #    url: jdbc:mysql://localhost:3306/hosoneu?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
  #    username: root
  #    password: 123456
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  datasource:
#    url: jdbc:mysql://120.79.88.98:3306/hosoneu?characterEncoding=utf-8&serverTimezone=GMT%2B8
    url: jdbc:mysql://localhost:3306/graduation_hosoneu?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: localhost
    password:
    port: 6379
mybatis:
  type-aliases-package: edu.neu.hoso.model
  mapper-locations: classpath:mapper/*.xml
